language: node_js
node_js:
  - "10"

jobs:
  include:
    - name: lint
      script: npm run lint
      if: type = pull_request
    - name: unit test
      script:
        - npm run test -- --coverage
        - npm run push-coverage
      if: type = pull_request
    - name: deploy
      stage: release
      if: branch = master AND type = push
      script: npm run deploy
    - name: coverage
      stage: release
      if: branch = master AND type = push
      script:
        - npm run test -- --coverage
        - npm run push-coverage